-- Lisää DROP TABLE lauseet tähän tiedostoon
DROP TABLE IF EXISTS Ilmoittautuminen CASCADE;
DROP TABLE IF EXISTS Suoritus CASCADE;
DROP TABLE IF EXISTS Toteutus CASCADE;
DROP TABLE IF EXISTS Opettaja CASCADE;
DROP TABLE IF EXISTS Oppilas CASCADE;
DROP TABLE IF EXISTS Kurssi CASCADE;

